#lanugage: php
build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run

filter:
    excluded_paths: [tests/*]

checks:
    php: true

tools:
    external_code_coverage: true
    php_cs_fixer: true
